<?php

/**
 * @file
 * Contains vvjs.module.
 *
 * Filename:     vvjs.module
 * Website:      https://www.flashwebcenter.com
 * Description:  template.
 * Developer:    Alaa Haddad https://www.alaahaddad.com.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_help().
 */
function vvjs_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.vvjs') {
    return _vvjs_helper_render_readme();
  }
  return NULL;
}

/**
 * Helper function to render README.md.
 */
function _vvjs_helper_render_readme() {
  $text = file_get_contents(__DIR__ . "/README.md");

  if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
    return '<pre>' . $text . '</pre>';
  }

  // Use the Markdown filter to render the README.
  $filter_manager = \Drupal::service('plugin.manager.filter');
  $settings = \Drupal::configFactory()
    ->get('markdown.settings')
    ->getRawData();
  $config = ['settings' => $settings];
  $filter = $filter_manager->createInstance('markdown', $config);
  return $filter->process($text, 'en');
}

/**
 * Implements hook_theme().
 */
function vvjs_theme($existing, $type, $theme, $path) {
  return [
    'views_view_vvjs' => [
      'variables' => [
        'view' => NULL,
        'rows' => [],
        'options' => [],
      ],
      'template' => 'views-view-vvjs',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for views_view_vvjs.
 */
function template_preprocess_views_view_vvjs(&$variables) {
  \Drupal::moduleHandler()->loadInclude('views', 'inc', 'views.theme');
  $handler = $variables['view']->style_plugin;

  $list_attributes = [];
  if ($handler->options['animation'] != 'none') {
    $list_attributes['data-animation'] = $handler->options['animation'];
  }

  $variables['list_attributes'] = new Attribute($list_attributes);

  $variables['settings'] = [
    'view_id' => $handler->view->dom_id,
    'animation' => $handler->options['animation'],
    'time_in_seconds' => $handler->options['time_in_seconds'],
    'navigation' => $handler->options['navigation'],
    'arrows' => $handler->options['arrows'],
    'unique_id' => $handler->options['unique_id'],
  ];

  template_preprocess_views_view_unformatted($variables);
}
