<?php

/**
 * @file
 * Contains vvjs.module.
 *
 * Filename:     vvjs.module
 * Website:      https://www.flashwebcenter.com
 * Description:  template.
 * Developer:    Alaa Haddad https://www.alaahaddad.com.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vvjs_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.vvjs') {
    return _vvjs_helper_render_readme();
  }
  return NULL;
}

/**
 * Helper function to render README.md.
 */
function _vvjs_helper_render_readme() {
  $text = file_get_contents(__DIR__ . "/README.md");

  if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
    return '<pre>' . $text . '</pre>';
  }

  // Use the Markdown filter to render the README.
  $filter_manager = \Drupal::service('plugin.manager.filter');
  $settings = \Drupal::configFactory()
    ->get('markdown.settings')
    ->getRawData();
  $config = ['settings' => $settings];
  $filter = $filter_manager->createInstance('markdown', $config);
  return $filter->process($text, 'en');
}

// Store vvjs preprocess theme functions in a separate .inc file.
\Drupal::moduleHandler()->loadInclude('vvjs', 'inc', 'vvjs.theme');

/**
 * Implements hook_theme().
 */
function vvjs_theme($existing, $type, $theme, $path) {
  return [
    'vvjs' => [
      'file' => 'vvjs.theme.inc',
    ],
  ];
}
